load("@rules_shell//shell:sh_test.bzl", "sh_test")
load(":stress.bzl", "stress_workload")

filegroup(
    name = "bare_inputs",
    srcs = glob(["bare/*.txt"]),
)

filegroup(
    name = "nested_individual_inputs",
    srcs = glob(["nested_files/**/*.txt"]),
)

filegroup(
    name = "source_tree_inputs",
    srcs = glob(
        ["source_dir/pkg_*"],
        exclude_directories = 0,
    ),
)

stress_workload(
    name = "stress_all",
    tool = "//tool:action-tool",
)

sh_test(
    name = "parse_timings_test",
    srcs = ["parse_timings_test.sh"],
    data = ["parse_timings.py"],
)
