load("@linux.bzl//:linux.bzl", "linux")
load("@bazel_lib//lib:run_binary.bzl", "run_binary")
load("@bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")

run_binary(
    name = "initramfs_target",
    args = [
        "$(location initramfs.cpio.zst)",
        "$(location //cmd/linux_actiond_guest:linux-actiond-guest)",
        "--file=$(location @e2fsprogs//:mkfs_ext4.stripped)=/sbin/mkfs.ext4",
    ],
    outs = ["initramfs.cpio.zst"],
    srcs = [
        "//cmd/linux_actiond_guest:linux-actiond-guest",
        "@e2fsprogs//:mkfs_ext4.stripped",
    ],
    tags = ["manual"],
    tool = "//tools:initramfs_newc",
)

platform_transition_filegroup(
    name = "initramfs_aarch64",
    srcs = [":initramfs_target"],
    target_platform = "//platforms:linux_aarch64_musl",
    visibility = ["//visibility:public"],
)

linux(
    name = "linux_kernel_aarch64",
    compact_repos = {
        "aarch64": "@actiond_vm_aarch64_compact",
    },
    config = "@actiond_vm_aarch64_kconfig//:kconfig",
    config_mode = "allnoconfig",
    extra_kconfigs = {
        "//kernel/actiondfs:Kconfig": "fs/actiondfs",
    },
    extra_srcs = ["//kernel/actiondfs:srcs"],
    image_format = "Image",
    source_repo = "@linux_6_18_2",
    visibility = ["//visibility:public"],
)

run_binary(
    name = "linux_kernel_aarch64_zst",
    args = [
        "$(location :linux_kernel_aarch64)",
        "$(location Image.zst)",
    ],
    outs = ["Image.zst"],
    srcs = [":linux_kernel_aarch64"],
    tool = "//tools:zstd_file",
    visibility = ["//visibility:public"],
)
