genrule(
    name = "initramfs",
    srcs = ["//cmd/linux_actiond:linux-actiond-guest-aarch64"],
    outs = ["initramfs.cpio"],
    cmd = "$(execpath //tools:initramfs_newc) $@ $(location //cmd/linux_actiond:linux-actiond-guest-aarch64)",
    tools = ["//tools:initramfs_newc"],
    visibility = ["//visibility:public"],
)

genrule(
    name = "linux_kernel",
    srcs = [
        "linux.config",
        "//tools:build_linux_kernel.sh",
        "//tools/docker:kernel.Dockerfile",
        "@linux_kernel_src//:Makefile",
        "@linux_kernel_src//:all",
    ],
    outs = ["Image"],
    cmd = "$(location //tools:build_linux_kernel.sh) $@ $(location linux.config) $(execpath @linux_kernel_src//:Makefile) $(location //tools/docker:kernel.Dockerfile)",
    tags = [
        "local",
        "manual",
        "no-sandbox",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "vm_bundle",
    srcs = [
        ":initramfs",
        ":linux_kernel",
    ],
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
