load(":exec_warmup.bzl", "exec_warmup")

platform(
    name = "actiond_linux_arm64_musl_exec",
    exec_properties = {
        "Arch": "arm64",
        "OSFamily": "Linux",
        "container-image": "docker://ubuntu:22.04",
    },
    parents = ["//platforms:linux_aarch64_musl"],
    visibility = ["//visibility:public"],
)

platform(
    name = "actiond_linux_x86_64_musl_exec",
    exec_properties = {
        "Arch": "amd64",
        "OSFamily": "Linux",
        "container-image": "docker://ubuntu:22.04",
    },
    parents = ["//platforms:linux_x86_64_musl"],
    visibility = ["//visibility:public"],
)

exec_warmup(
    name = "llvm_exec_warmup",
    deps = [
        "@llvm-project//llvm:llvm-min-tblgen",
    ],
)
