load("@rules_zig//zig:defs.bzl", "zig_binary")

zig_binary(
    name = "linux-actiond",
    main = "main.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
    deps = ["//src:actiond"],
)

genrule(
    name = "linux-actiond-standalone_pkg",
    srcs = [
        ":linux-actiond",
        "//runtimes:runtimes_squashfs",
    ],
    outs = ["linux-actiond-standalone"],
    cmd = """
set -euo pipefail
cp "$(location :linux-actiond)" "$@"
chmod +w "$@"
"$(execpath @llvm//tools:llvm-objcopy)" --add-section .actiond.runtimes="$(location //runtimes:runtimes_squashfs)" "$@"
chmod +x "$@"
""",
    executable = True,
    target_compatible_with = ["@platforms//os:linux"],
    tools = ["@llvm//tools:llvm-objcopy"],
    visibility = ["//visibility:public"],
)
