load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@rules_zig//zig:defs.bzl", "zig_binary")
load("//tools:zig_embedded_assets.bzl", "zig_embedded_assets")

zig_binary(
    name = "windows-actiond",
    linkopts = [
        "-flto",
        "-lcomputecore",
        "-lntdll",
        "-lole32",
        "-lws2_32",
    ],
    main = "main.zig",
    strip_debug_symbols = True,
    target_compatible_with = ["@platforms//os:windows"],
    visibility = ["//visibility:public"],
    zigopts = [
        "-flld",
        "-flto",
    ],
    deps = [
        ":embedded_assets",
        "//src:actiond",
    ],
)

alias(
    name = "embedded_initramfs",
    actual = select({
        "@platforms//cpu:aarch64": "//vm:initramfs_aarch64",
        "@platforms//cpu:x86_64": "//vm:initramfs_x86_64",
    }),
)

alias(
    name = "embedded_kernel",
    actual = select({
        "@platforms//cpu:aarch64": "//vm:linux_kernel.image",
        "@platforms//cpu:x86_64": ":embedded_kernel_x86_64",
    }),
)

filegroup(
    name = "embedded_kernel_x86_64",
    srcs = ["//vm:linux_kernel.vm_linux"],
    output_group = "vmlinux",
)

zig_embedded_assets(
    name = "embedded_assets",
    initramfs = ":embedded_initramfs",
    kernel = ":embedded_kernel",
    runtime_image = "//runtimes:runtimes_squashfs",
)

platform_transition_binary(
    name = "windows-actiond_windows_arm64",
    basename = "windows-actiond_windows_arm64.exe",
    binary = ":windows-actiond",
    target_platform = "@llvm//platforms:windows_arm64",
    visibility = ["//visibility:public"],
)

platform_transition_binary(
    name = "windows-actiond_windows_x86_64",
    basename = "windows-actiond_windows_x86_64.exe",
    binary = ":windows-actiond",
    target_platform = "@llvm//platforms:windows_x86_64",
    visibility = ["//visibility:public"],
)
