load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@rules_zig//zig:defs.bzl", "zig_binary")

zig_binary(
    name = "linux-actiond-guest",
    main = "main.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
    deps = ["//src:actiond"],
)

platform_transition_binary(
    name = "linux-actiond-guest-aarch64-raw",
    basename = "linux-actiond-guest-aarch64-raw",
    binary = ":linux-actiond-guest",
    target_platform = "//platforms:linux_aarch64",
)

genrule(
    name = "linux-actiond-guest-aarch64",
    outs = ["linux-actiond-guest-aarch64.bin"],
    cmd = """
set -euo pipefail
cp "$(execpath :linux-actiond-guest-aarch64-raw)" "$@"
chmod +w "$@"
"$(execpath @llvm//tools:llvm-strip)" --strip-all "$@"
chmod +x "$@"
    """,
    executable = True,
    tools = [
        ":linux-actiond-guest-aarch64-raw",
        "@llvm//tools:llvm-strip",
    ],
    visibility = ["//visibility:public"],
)
