load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_configure_binary")

zig_binary(
    name = "linux-actiond-guest",
    main = "main.zig",
    deps = ["//src:actiond"],
    visibility = ["//visibility:public"],
)

zig_configure_binary(
    name = "linux-actiond-guest-aarch64",
    actual = ":linux-actiond-guest",
    target = "//platforms:linux_aarch64",
    zig_version = "0.16.0",
    visibility = ["//visibility:public"],
)
