load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_configure_binary", "zig_test")

exports_files([
    "build_linux_kernel.sh",
])

zig_binary(
    name = "initramfs_newc",
    linkopts = ["-lc"],
    main = "initramfs_newc.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
    deps = ["@zstd"],
)

zig_binary(
    name = "e2e_action_tool",
    main = "e2e_action_tool.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
)

zig_test(
    name = "e2e_action_tool_tests",
    main = "e2e_action_tool.zig",
)

zig_binary(
    name = "embed_payload",
    main = "embed_payload.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
    deps = ["//src:actiond"],
)

zig_binary(
    name = "sqfs_pack",
    linkopts = ["-lc"],
    main = "sqfs_pack.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
    deps = ["@zstd"],
)

zig_binary(
    name = "zstd_file",
    linkopts = ["-lc"],
    main = "zstd_file.zig",
    strip_debug_symbols = True,
    visibility = ["//visibility:public"],
    deps = ["@zstd"],
)

zig_configure_binary(
    name = "e2e_action_tool_linux_aarch64",
    actual = ":e2e_action_tool",
    target = "//platforms:linux_aarch64",
    visibility = ["//visibility:public"],
    zig_version = "0.16.0",
)

zig_configure_binary(
    name = "e2e_action_tool_linux_x86_64",
    actual = ":e2e_action_tool",
    target = "//platforms:linux_x86_64",
    visibility = ["//visibility:public"],
    zig_version = "0.16.0",
)

zig_test(
    name = "initramfs_newc_tests",
    linkopts = ["-lc"],
    main = "initramfs_newc.zig",
    deps = ["@zstd"],
)

zig_test(
    name = "sqfs_pack_tests",
    linkopts = ["-lc"],
    main = "sqfs_pack.zig",
    deps = ["@zstd"],
)

zig_test(
    name = "zstd_file_tests",
    linkopts = ["-lc"],
    main = "zstd_file.zig",
    deps = ["@zstd"],
)
