"""Build settings and generated Zig build options."""

load("@bazel_skylib//rules:common_settings.bzl", "BuildSettingInfo")

def _bool_flag_impl(ctx):
    return [BuildSettingInfo(value = ctx.build_setting_value)]

bool_flag = rule(
    implementation = _bool_flag_impl,
    build_setting = config.bool(flag = True),
)

def _zig_bool(value):
    return "true" if value else "false"

def _zig_build_options_impl(ctx):
    executor_timing_logs = ctx.attr.executor_timing_logs[BuildSettingInfo].value
    ctx.actions.write(
        output = ctx.outputs.out,
        content = """// Generated by Bazel. Do not edit.
pub const executor_timing_logs = {};
""".format(_zig_bool(executor_timing_logs)),
    )
    return [DefaultInfo(files = depset([ctx.outputs.out]))]

zig_build_options = rule(
    implementation = _zig_build_options_impl,
    attrs = {
        "executor_timing_logs": attr.label(mandatory = True),
        "out": attr.output(mandatory = True),
    },
)
