load("@bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@codesign.bzl", "codesign")
load("@rules_cc//cc:objc_library.bzl", "objc_library")
load("@rules_zig//zig:defs.bzl", "zig_binary")
load("//tools:zig_embedded_assets.bzl", "zig_embedded_assets")

objc_library(
    name = "vz_bridge",
    srcs = ["vz_bridge.m"],
    copts = [
        "-fblocks",
        "-fobjc-arc",
    ],
    sdk_frameworks = [
        "Foundation",
        "Virtualization",
    ],
    target_compatible_with = ["@platforms//os:macos"],
)

zig_binary(
    name = "darwin-actiond-bin",
    main = "main.zig",
    strip_debug_symbols = True,
    target_compatible_with = ["@platforms//os:macos"],
    deps = [
        ":embedded_assets",
        ":vz_bridge",
        "//src:actiond",
    ],
)

zig_embedded_assets(
    name = "embedded_assets",
    initramfs = "//vm:initramfs_aarch64",
    kernel = "//vm:linux_kernel.image",
    runtime_image = "//runtimes:runtimes_squashfs_aarch64",
)

codesign(
    name = "darwin-actiond",
    binary = ":darwin-actiond-bin",
    binary_identifier = "darwin-actiond",
    entitlements = "darwin-actiond.entitlements",
    target_compatible_with = ["@platforms//os:macos"],
    visibility = ["//visibility:public"],
)

platform_transition_binary(
    name = "darwin-actiond_macos_arm64",
    basename = "darwin-actiond_macos_arm64",
    binary = ":darwin-actiond",
    target_platform = "@llvm//platforms:macos_arm64",
    visibility = ["//visibility:public"],
)
